<section class="py-5 text-center container">
    <h1>Nos utilisateurs</h1>
</section>

<div class="d-flex flex-wrap">
<?php foreach ($allUsers as $user) : ?>
    <div class="card my-3 mx-auto" style="width: 18rem; height: 35rem;">
        <div class="card-img-top avatar">
            <img src="<?= $user->avatar ?>" class="avatar-user" alt="...">
        </div>
        <div class="card-body d-flex flex-column align-content-between">
            <p class="card-text">ID : <span class="badge bg-secondary"><?= $user->id ?></span></p>
            <h5 class="card-title mb-3"><?= $user->first_name . ' ' . $user->last_name ?></h5>
            <p class="card-text"><i class="fa-solid fa-at i-email"></i> <?= $user->email ?></p>
            <p class="card-text"><i class="fa-solid fa-location-dot i-street"></i> <?= $user->street . ' ' . $user->city ?></p>
            <a href="index.php?url=contact&id=<?= $user->id ?>" class="btn btn-primary">Contact</a>
        </div>
    </div>
    <?php endforeach; ?>
</div>