<section class="py-5 text-center container">
    <h1 class="fw-light">Nos utilisateurs</h1>
</section>

<div class="d-flex flex-wrap">
<?php foreach ($allUsers as $user) : ?>
    <div class="card m-3" style="width: 18rem;">
        <div class="card-img-top avatar">
            <img src="<?= $user->avatar ?>" class="avatar-user" alt="...">
        </div>
        <div class="card-body">
            <p class="card-text">ID : <span class="badge bg-secondary"><?= $user->id ?></span></p>
            <h5 class="card-title"><?= $user->first_name . ' ' . $user->last_name ?></h5>
            <p class="card-text"><?= $user->email ?></p>
            <p class="card-text"><?= $user->street . ' ' . $user->city ?></p>
            <a href="index.php?url=contact&id=<?= $user->id ?>" class="btn btn-primary">Contact</a>
        </div>
    </div>
    <?php endforeach; ?>
</div>