<!doctype html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="./assets/css/style.css" type="text/css" />
    <title>Document</title>
</head>
<body>
    <header>
        <nav>
            <ul>
                <li><a href="index.php?url=login&q=connexion">Connexion</a></li>
                <li><a href="index.php?url=login&q=inscription">Inscription</a></li>
            </ul>
        </nav>
        <form method="post">
            <input type="hidden" name="deco" value="deco"/>
            <button type="submit"> deconnexion</button>
        </form>
    </header>
    <main>
    <?= $content ?>
    </main>
    <footer>
        <p>Mon footer</p>
    </footer>
</body>
</html>