<?php if($_GET['q'] !== 'inscription'): ?>
<form method='POST'> 
    <fieldset>
        <legend>Formulaire de connexion</legend> 
        <p style='color:red;'><?= $error ?? '' ?></p>
        <div class="group">
            <label for="email">Email</label>
            <input type="text" name="email" id="email" autocomplete="off"/>            
        </div>
        <div class="group">
            <label for="pass">Mot de passe</label>
            <input type="password" name="pass" id="pass"/>            
        </div>
        <input type="hidden" name="form" value='connexion'> <!-- champs qui permet de distinguer les formulaire -->
        <input type="submit" value="Connexion"/>
        <nav>
            <ul>
                <li><a href="index.php?url=login&q=inscription">Créer un compte</a></li>
            </ul>
        </nav>
    </fieldset>
</form>
<?php else: ?>
<form method='POST'> 
    <noscript>
        <p> <?= $error ?> </p>
    </noscript>
    <fieldset>
        <legend>Formulaire d'inscription</legend>
        <div class="group">
            <label for="nom">Nom</label>
            <input type="text" name="nom" id="email" autocomplete="off"/>            
        </div>
        <div class="group">
            <label for="prenom">Prénom</label>
            <input type="text" name="prenom" id="email" autocomplete="off"/>            
        </div>
        <div class="group">
            <label for="email">Email</label>
            <input type="text" name="email" id="email" autocomplete="off"/>            
        </div>
        <div class="group">
            <label for="pass">Mot de passe</label>
            <input type="password" name="pass" id="pass"/>            
        </div>
        <div class="group">
            <label for="confirm">Confirmer le mot de passe</label>
            <input type="password" name="confirm" id="confirm"/>            
        </div>
        <input type="hidden" name="form" value='inscription'> <!-- champs qui permet de distinguer les formulaire -->
        <input type="submit" value="Inscription"/>
        <nav>
            <ul>
                <li><a href="index.php?url=login&q=connexion">J'ai déja un compte</a></li>
            </ul>
        </nav>
    </fieldset>
</form>
<?php endif; ?>
