<!doctype html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Super site</title>
</head>
<body>
    <header>
        <h1>Super site</h1>
        <nav>
            <a href="index.php?page=home">Page d'accueil</a>
            <a href="index.php?page=about">À propos</a>
        </nav>
    </header>
    
    <main>
        <?php require $template; ?>
    </main>
    
    <footer>
        Copyright 2022
    </footer>
</body>
</html>