<h1>Contact</h1>

<p>Ma page contact</p>

<section class="">
    <div class="mb-4">
        <h4>Adresse</h4>
        <p>27 rue Ferdinant de Lesspes 35000 Rennes</p>
    </div>
    <div>
        <h4>Contacts</h4>
        <a href="mailto : mohamed.benallal.pro@gmail.com" style="text-transform: none">mohamed.benallal.pro@gmail.com</a>
        <br>
        <a href="tel:0610580000">06.10.58.00.00</a>
    </div>
</section>