<div class="msg-page mt-5">
    <h1 class="mb-5">Nom de la Room</h1>
    <div class="msg-show">
        <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Minus, architecto!</p>
        <p>Lorem ipsum dolor sit amet.</p>
        <p>Lorem ipsum dolor sit amet consectetur.</p>
        <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Sapiente.</p>
        <p>Lorem ipsum dolor sit.</p>
    </div>
    <div class="msg-new">
        <form method="POST">
            <label class="form-label" for="message">Nouveau message</label>
            <input class="form-control mb-3" type="text" name="message" id="msg-add">
            <input class="btn btn-outline-light" type="submit" value="Send">
        </form>
    </div>

</div>